spring:
  jackson:
    date-format: yyyy-MM-dd
  datasource:
    name: dataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    max-active: 100
    initial-size: 2
    min-idle: 2
    max-idle: 10
    test-while-idle: true
    test-on-borrow: true
    validation-query: "select  1 from dual"
    initialize: false


server:
  port: 8082

log:
  path: D:/logs
  name: jpa